[project]
name = "down-to-earth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
    "scikit-learn>=1.6.1",
    "torch>=2.8.0",
    "tqdm>=4.70.1",
]

[project.scripts]
down-to-earth = "down_to_earth:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
